name: Testing playground for Github Actions

on:
  schedule:
    - cron: '0 16 * * *'   # 8 AM Pacific
    - cron: '0 22 * * *'   # 3 PM Pacific
  workflow_dispatch:

jobs:
  run-kaggle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install kaggle nbconvert ipykernel papermill

    - name: Set up Kaggle credentials
      run: |
        mkdir -p ~/.kaggle
        echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: List files for debugging
      run: ls -lhR .github/workflows/

    - name: Run notebook and show only print() output
      id: run_notebook1
      run: |
        echo "â–¶ï¸ Running notebook with clean output"
        pip install papermill > /dev/null 2>&1
        papermill .github/workflows/automated-tempalert-short.ipynb \
                /tmp/output.ipynb \
                --log-output --no-progress-bar 2>&1 | grep -E "ğŸ”¥|âœ…|âš ï¸|âŒ|ğŸ”˜|ğŸ‘€|â˜‘ï¸|Notebook started|Logged in"

